spring.application.name=TalentIq

server.port=${PORT:1818}

# ===============================
# Gemini AI
# ===============================
spring.ai.model.chat=google-genai

spring.ai.google.genai.api-key=${GENAI_API_KEY}

spring.ai.google.genai.chat.model=gemini-3.6-flash
spring.ai.google.genai.chat.temperature=0.2
spring.ai.google.genai.chat.response-mime-type=application/json

# ===============================
# PDF Upload
# ===============================
spring.servlet.multipart.max-file-size=25MB
spring.servlet.multipart.max-request-size=25MB

# ===============================
# MySQL Database (Aiven)
# ===============================
spring.datasource.url=jdbc:mysql://talentiq-mysql-talentiq.j.aivencloud.com:17367/defaultdb?ssl-mode=REQUIRED

spring.datasource.username=avnadmin
spring.datasource.password=${DB_PASSWORD}

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# ===============================
# JPA / Hibernate
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.open-in-view=false
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

logging.level.org.springframework.security=DEBUG

# ===============================
# Gmail SMTP
# ===============================
spring.mail.host=smtp.gmail.com
spring.mail.port=587

spring.mail.username=talentiqteam@gmail.com
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.connectiontimeout=5000
spring.mail.properties.mail.smtp.timeout=5000
spring.mail.properties.mail.smtp.writetimeout=5000
